# Can everyone edit?
public_write: true

# Can anyone reister users?
public_registration: true

# Permalink of the home page.
home_page: Home

# Will be appended to the <title> tag.
site_name: Go, Kii!

# The name of the template, matching a directory name in app/templates.
template: default

# Choose the markup language you want to use.
# Available: default, redcloth
markup: default

# The name of the custom CSS file. Resolves to public/stylesheets.
# site_css: site.css

# The name of the custom logo. Resolves to public/images
# site_logo: "site_logo.png"